### ISSUE TITLE
start_avm.sh fails to start when DEBUG is not defined

### ISSUE THREAD

**Issue by mz-pdm** [slp/start-avm#6]
```
start_avm.sh: line 46: [: ==: unary operator expected
```

The fix, defining `DEBUG` environment variable, is contained among other changes in
https://github.com/slp/start-avm/pull/5/commits/c7ad440fdb40cb3e90a300f9cc0b4a48538fdb8c

**Comment by slp** [comment]
I've just merged #5, so should be fixed now. Thanks!
